Repository emilps/fjelltg, pull requests merged in 2019-12, with the labels that each got.

#17 Add projects to cms
  src/cms/cms.js
  src/cms/preview-templates/ProjectPreview.js
  src/components/Footer.js
  src/components/Navbar.js
  src/components/ProjectRoll.js
  src/pages/project/index.js
  src/templates/project.js
  static/admin/config.yml
Labels: CMS, enhancement

#22 Feat/index image
  src/components/IndexImage.js
  src/components/all.sass
  src/templates/index-page.js
Labels: Design, Frontend, enhancement

#23 Feat/project design
  src/components/PreviewCompatibleImage.js
  src/components/ProjectRoll.js
  src/components/all.sass
  src/pages/project/index.js
Labels: Design, Frontend, enhancement

#24 feat/page jumbotron
  src/components/PageJumbotron.js
  src/components/all.sass
  src/pages/product/index.js
  src/pages/project/index.js
Labels: Frontend, enhancement
